service: questionnaire # NOTE: update this with your service name

provider:
  name: aws
  runtime: go1.x
  role: arn:aws:iam::168943165440:role/service-role/goLangWkhtmltox
  stage: dev
  region: eu-central-1
  memorySize: 128
  timeout: 10

package:
  individually: true
  exclude:
    - ./**
      
functions:
  pdf:
    handler: bin/pdfgenerator
    package:
      include:
        - bin/pdfgenerator
        - bin/wkhtmltopdf
    name: ${self:service}-pdf-${self:provider.stage}
    events:
      - http:
          path: pdf
          method: POST
          integration: lambda
          request:
            template:
              application/json: '$input.body'
  inlinePdf:
    handler: bin/inlinepdf
    package:
      include:
        - bin/inlinepdf
    name: ${self:service}-pdf-inline-${self:provider.stage}
    events:
      - http:
          path: inlinepdf
          method: POST
          integration: lambda
          request:
            template:
              application/json: '$input.body'
    TracingConfig: 
      Mode: Active